runtime: nodejs14

handlers:
  - url: /static
    static_dir: client/build/static

  - url: /(.*\.(json|ico|js))$
    static_files: client/build/\1
    upload: client/build/.*\.(json|ico|js)$

  - url: /(.*\.(css|png|jpg|gif|woff|woff2|ttf|svg|eot))$
    static_files: client/build/\1
    upload: client/build/.*\.(css|png|jpg|gif|woff|woff2|ttf|svg|eot)$

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
